import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
const items=[
{code:"SA-07",title:"Namib Desert & Tiger Bay",meta:"5 days / 4 nights · From USD 1,400",text:"Dunes, ghost towns and starry nights on Angola's wild Atlantic coast.",image:"/sungos/01.webp",href:"/experiencias/namib-desert-tiger-bay"},
{code:"SA-09",title:"Southern Angola Expedition",meta:"8 days / 7 nights · From USD 3,500",text:"From Luanda to Lubango, Serra da Leba, Iona and Baía dos Tigres.",image:"/sungos/15.webp",href:"/experiencias/southern-angola-expedition"},
{code:"SA-10",title:"Far & Wild Private Expedition",meta:"12 days / 11 nights · From USD 12,967",text:"A private journey across Angola's most contrasting landscapes.",image:"/sungos/80.webp",href:"/experiencias/far-and-wild"},
{code:"SA-04",title:"Kalandula Falls Escape",meta:"3 days / 2 nights · From USD 500",text:"Two nights beside one of Africa's mightiest waterfalls.",image:"/sungos/62.webp",href:"/experiencias/kalandula-falls"}
];
export default function Experiences(){return <section id="experiences" className="bg-[#171714] px-6 py-24 text-white lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-[11px] uppercase tracking-[.3em] text-white/40">Angola Experience Collection</p><h2 className="mt-5 max-w-3xl text-5xl font-medium leading-[.94] tracking-[-.04em] sm:text-6xl">Journeys designed to make <span className="font-light italic">Angola unforgettable.</span></h2></div><p className="max-w-sm text-sm leading-6 text-white/45">Ready-to-sell journeys for travellers, travel advisors and operators — with practical local delivery behind every itinerary.</p></div><div className="mt-16 grid gap-px border border-white/10 bg-white/10 md:grid-cols-2">{items.map((x,i)=><Link href={x.href} key={x.code} className={`group relative overflow-hidden bg-[#171714] p-5 ${i===0?'md:col-span-2':''}`}><div className={`relative overflow-hidden ${i===0?'aspect-[2.15/1]':'aspect-[1.25/1]'}`}><Image src={x.image} alt={x.title} fill className="object-cover opacity-75 transition duration-700 group-hover:scale-105 group-hover:opacity-90" sizes="(max-width:768px) 100vw, 50vw"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/15 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 lg:p-8"><div className="flex items-end justify-between gap-5"><div><p className="text-[10px] uppercase tracking-[.25em] text-white/45">{x.code}</p><h3 className="mt-2 max-w-2xl text-3xl font-medium tracking-tight sm:text-4xl">{x.title}</h3><p className="mt-2 text-xs uppercase tracking-[.12em] text-white/55">{x.meta}</p><p className="mt-3 max-w-xl text-sm leading-6 text-white/65">{x.text}</p></div><span className="flex h-11 w-11 shrink-0 items-center justify-center bg-white text-black"><ArrowUpRight size={18}/></span></div></div></div></Link>)}</div></div></section>}
